### ISSUE TITLE
known issue with atom CLI

### ISSUE THREAD

**Issue by duncdrum** [semantic-release/apm#10]
see  atom/atom#18318
when using the @semantic-release/apm plugin via a deploy stage on travis the atom cli appears to be missing.
You can rectify this by setting:
```
before_script:
	  - export PATH=$PATH:~/atom/usr/bin
```

in your `travis.yml`

**Comment by pvdlg** [comment]
I think this is related to the Atom CI script. See https://github.com/atom/ci/issues/81

In any case the problem is not in this plugin, so there is nothing we can do about it.
